workflows:
  spotify-workflow:
    name: Spotify Pipeline
    scripts:
        - name: CICD Started
        - script: echo "Welcome to your CICD set up"
    publishing:
      email:
        recipients:
           - shivamrishisr@gmail.com
      
