workflows:
  spotify-workflow:
    name: Spotify Pipeline
    scripts:
        - name: CICD Started
          script: echo "Welcome to your CICD set up"
        - name: Build spotify
          script: xcodebuild build -workspace "Spotify.xcworkspace" -scheme "Spotify" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
           - shivamrishisr@gmail.com
      
